### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by RichardTezbirr** [eisberg-labs/ngx-barcode-scanner#10]
Steps to reproduce: 

1. npm install {packageName}

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@eisbeg-labs%2fngx-barcode-scanner - Not found
> npm ERR! 404 
> npm ERR! 404  '@eisbeg-labs/ngx-barcode-scanner@*' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

2.  Npm install {gitUrl}

> removed 1 package, and audited 1630 packages in 9s
> 
> 90 packages are looking for funding
>   run `npm fund` for details
> 
> 13 vulnerabilities (10 moderate, 3 high)

in other words, succesfull.

3. import {NgxBarcodeScannerModule} from '@eisberg-labs/ngx-barcode-scanner'; (in app.module.ts)

> Cannot find module '@eisberg-labs/ngx-barcode-scanner' or its corresponding type declarations.ts(2307)

I have never encountered such an error, when I look to node modules, package exists, I check names and all is correct, so why do you think it is not able to find the package ? 

> 4.  delete node modules and package.lock.json, run npm install.

Comming back to step 1-3 again (without change);

**Comment by amarjanica** [comment]
Hi Richard, thanks for reporting the issue! There was a typo in the docs:
Previously....`npm install *@eisbeg-labs*/ngx-barcode-scanner --save`
But should be...`npm install @eisberg-labs/ngx-barcode-scanner --save`
Ill update the doc shortly.

**Comment by RichardTezbirr** [comment]
Hi there,

I have tried it, but I got some dependancy misunderstanding:

> npm ERR! Found: @angular/common@11.1.2
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"~11.1.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"^9.0.5" from @eisberg-labs/ngx-barcode-scanner@1.0.0
> npm ERR! node_modules/@eisberg-labs/ngx-barcode-scanner
> npm ERR!   @eisberg-labs/ngx-barcode-scanner@"*" from the root project

When I create entire new project Angular.

> npm ERR! While resolving: something@0.0.0
> npm ERR! Found: @angular/common@12.2.2
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"~12.2.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"^9.0.5" from @eisberg-labs/ngx-barcode-scanner@1.0.0
> npm ERR! node_modules/@eisberg-labs/ngx-barcode-scanner
> npm ERR!   @eisberg-labs/ngx-barcode-scanner@"*" from the root project

Is this related to a package, or to an angular ?

**Comment by amarjanica** [comment]
Probably related to old angular version, latest published package supports v9. Ill have to check and bump angular

**Comment by RichardTezbirr** [comment]
That would be great, as I have checked, many barcode scanners have similar
problem and those which versioning is okey, does not work very well for any
usecase.

**Comment by amarjanica** [comment]
I update to version 2.0.0. Lib uses min angular 11, also fixed security vulnerabilities with npm audit. Tests pass, demo project runs. Let me know if it's ok, thanks!

**Comment by RichardTezbirr** [comment]
Hi there, it works now. 
Thank you very much for fixing it.
However it might not work with angular/cli^12.2.0. But version 11 works fine.
